project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: false
  open-graph: false
  repo-actions: [issue]
  navbar:
    background: primary
    search: false
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]