name: Lint
on:  [workflow_dispatch, pull_request, push]

jobs:
  nbqa:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3 

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'
        cache: "pip"
        cache-dependency-path: settings.ini

    - name: Install lib
      run: |
        pip install -e .[dev]

    - name: Check nbs are clean
      run: ./scripts/check_nbs_clean.sh
      shell: bash

    - name: Run flake8
      run: nbqa flake8 nbs/*.ipynb

    - name: Run Mypy
      run: nbqa mypy nbs/*.ipynb --ignore-missing-imports
